### ISSUE TITLE
Uncaught TypeError: e.item.getURI is not a function

### ISSUE THREAD

**Issue by AndreaVitale** [joshjensen/related-split-view#2]
This happens when I try to close a previous opened "git-control" tab.

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [related-split-view](https://github.com/joshjensen/related-split-view) package, v0.2.1
### Stack Trace

Uncaught TypeError: e.item.getURI is not a function

```
At /Users/Andrea/.atom/packages/related-split-view/lib/related-split-view.coffee:143

TypeError: e.item.getURI is not a function
    at Object.module.exports.MvcSplit.onWillRemoveItemLeftPaneItem (/Users/Andrea/.atom/packages/related-split-view/lib/related-split-view.coffee:143:31)
    at /Users/Andrea/.atom/packages/related-split-view/lib/related-split-view.coffee:118:89
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:389:20)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:464:16)
    at atom-tabs.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:695:17)
```
### Commands

```
  4x -0:09.2.0 core:cancel (ul.list-inline.tab-bar.inset-panel)
     -0:04.4.0 tabs:close-all-tabs (li.tab.sortable.right-clicked)
     -0:03.8.0 core:cancel (ul.list-inline.tab-bar.inset-panel)
```
### Config

``` json
{
  "core": {
    "destroyEmptyPanes": false
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.26
docblockr, v0.7.3
git-control, v0.4.0
hyperclick, v0.0.35
related-split-view, v0.2.1
terminal-plus, v0.14.5
titanium-alloy, v0.9.0

# Dev
No dev packages
```

**Comment by stephenfeather** [comment]
I'll add some information. Occurs if Atom has opened Settings on its own (prompt to update) or About has been opened and you try to close that tab, opened in the left full height pane. Similar relationship as @AndreaVitale has.

Atom 1.11.0-beta5
OSX Sierra 10.12 Final

**Comment by joshjensen** [comment]
Fixed

**Comment by jasonkneen** [comment]
This is still happening -- 1.19.0
